// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) ([]CreateFeedFollowRow, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteFeedFollowByUserAndUrl(ctx context.Context, arg DeleteFeedFollowByUserAndUrlParams) error
	GetFeedByURL(ctx context.Context, url string) (Feed, error)
	GetFeedFollowsForUser(ctx context.Context, name string) ([]GetFeedFollowsForUserRow, error)
	GetFeeds(ctx context.Context) ([]Feed, error)
	GetNextFeedToFetch(ctx context.Context) (Feed, error)
	GetPostsForUser(ctx context.Context, arg GetPostsForUserParams) ([]GetPostsForUserRow, error)
	GetUrlByEntryNumber(ctx context.Context, entryNumber sql.NullInt32) (string, error)
	GetUser(ctx context.Context, name string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	MarkFeedFetched(ctx context.Context, arg MarkFeedFetchedParams) error
	ResetUsers(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
